Ultimos cambios

diff --git a/android/gradlew b/android/gradlew
--- a/android/gradlew
+++ b/android/gradlew
@@ -15,8 +15,6 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
-# SPDX-License-Identifier: Apache-2.0
-#
 
 ##############################################################################
 #
@@ -57,12 +55,11 @@
 #       Darwin, MinGW, and NonStop.
 #
 #   (3) This script is generated from the Groovy template
-#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
 #       within the Gradle project.
 #
 #       You can find Gradle at https://github.com/gradle/gradle/.
 #
-##############################################################################
 
 # Attempt to set APP_HOME
 
@@ -85,9 +82,7 @@ done
 # This is normally unused
 # shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
-# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
-APP_HOME=$( cd -P "${APP_HOME:-./}" > /dev/null && printf '%s
-' "$PWD" ) || exit
+APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
@@ -134,13 +129,10 @@ location of your Java installation."
     fi
 else
     JAVACMD=java
-    if ! command -v java >/dev/null 2>&1
-    then
-        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
-    fi
 fi
 
 # Increase the maximum file descriptors if we can.
@@ -148,7 +140,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
     case $MAX_FD in #(
       max*)
         # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
-        # shellcheck disable=SC2039,SC3045
+        # shellcheck disable=SC3045
         MAX_FD=$( ulimit -H -n ) ||
             warn "Could not query maximum file descriptor limit"
     esac
@@ -156,7 +148,7 @@ if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
       '' | soft) :;; #(
       *)
         # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
-        # shellcheck disable=SC2039,SC3045
+        # shellcheck disable=SC3045
         ulimit -n "$MAX_FD" ||
             warn "Could not set maximum file descriptor limit to $MAX_FD"
     esac
@@ -234,19 +226,91 @@ fi
 #
 # but POSIX shell has neither arrays nor command substitution, so instead we
 # post-process each arg (as a line of input to sed) to backslash-escape any
-# character that might be a shell metacharacter, then use eval to reverse
-# that process (while maintaining the separation between arguments), and wrap
-# the whole thing up as a single "set" statement.
+# character that might be a shell metacharacter, then use eval to parse
+# them into the shell's argument list.
 #
-# This will of course break if any of these variables contains a newline or
-# an unmatched quote.
-#
+# Usage: parseArgs string-to-parse
+parseArgs ()
+{
+    json=false
+    literalEqualSigns=false
+    while [ "$#" -gt 0 ]
+    do
+        arg=$1
+        case $arg in #(
+          --*=* )
+            set -- "${arg%%=*}" "${arg#*=}" "$@"
+            ;;
+          --json )
+            json=true
+            ;;
+          --literal-equal-signs )
+            literalEqualSigns=true
+            ;;
+        esac
+        shift
+    done
 
-eval "set -- $(
-        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
-        xargs -n1 |
-        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
-        tr '\n' ' '
-    )" '"$@"'
+    str="$*"
+
+    # When no JSON is requested, take the regular route.
+    if [ "$json" = false ]
+    then
+        parseArgsDefault "$str"
+        return
+    fi
+
+    # Parse arguments in JSON format
+    newArgs=
+    while
+        # Grab the next string, accounting for both single and double quotes.
+        # (Note that the loop will always be entered with the string starting with a quote.)
+        case $str in #(
+          \'* ) # single-quoted string
+            str=${str#\'}
+            arg=${str%%\'*}
+            str=${str#"$arg"*}
+            ;;
+          * ) # double-quoted or unquoted string
+            arg=${str%%[[:space:]]*}
+            str=${str#"$arg"*}
+            ;;
+        esac
+
+        # If there were any arguments, strip a leading space before adding
+        # the next one.
+        case $newArgs in #(
+          *[![:space:]]* ) newArgs="$newArgs " ;; #(
+          * ) newArgs= ;;
+        esac
+        newArgs="$newArgs$arg"
+        [ ${#str} -gt 0 ]
+    do
+        str=${str#[[:space:]]}
+    done
+
+    # Update the positional parameters with the new arguments.
+    eval "set -- $newArgs"
+}
+
+parseArgsDefault ()
+{
+    str="$*"
+
+    # Escape application args
+    save () {
+        for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
+        echo " "
+    }
+    APP_ARGS=`save "$@"`
+
+    # Collect all arguments for the java command:
+    eval "set -- $APP_ARGS"
+}
+
+# by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
+if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$PWD" ]; then
+  cd "$(dirname "$0")"
+fi
 
 exec "$JAVACMD" "$@"
